# Use an official PHP image as base
FROM php:8.0-fpm

# Set the working directory
WORKDIR /var/www/html

COPY . /var/www/html

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libzip-dev \
    libcurl4-openssl-dev \
    libicu-dev \
    libgd-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql zip opcache intl gd exif mysqli

# Install cURL extension separately
RUN docker-php-ext-install curl

# Install Composer globally
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set Composer environment variables
ENV COMPOSER_ALLOW_SUPERUSER 1
ENV PATH "${PATH}:/root/.composer/vendor/bin"

# Install composer dependencies
RUN composer install --no-dev --optimize-autoloader --ignore-platform-reqs

# Set folder permissions (adjust the user and group based on your setup)
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

# Expose port 80 and start php-fpm server
EXPOSE 80
CMD ["php-fpm"]

