version: '3'
services:
  php-apache:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: MfIclv+8JjFpt7NxiLqXuS7lfyoy1gQQILEIlqGYHzw=
      MYSQL_DATABASE: 6valy_db
      MYSQL_PASSWORD: dtkLpP69q4QzLIgP

